-- Clear existing templates to avoid duplicates (optional, use with caution)
-- delete from bullet_templates;

INSERT INTO bullet_templates (theme, fi_text, en_text, tags) VALUES
-- A. DISCOVERY
('Discovery', 'A/B‑testaus', 'A/B testing', '{discovery, testing}'),
('Discovery', 'Analytiikan tarkistus', 'Analytics Review', '{discovery, data}'),
('Discovery', 'Asiakaspolku', 'Customer Journey', '{discovery, ux}'),
('Discovery', 'Asiakassegmentit', 'Customer Segments', '{discovery, business}'),
('Discovery', 'Asiakasymmärrys', 'Customer Insight', '{discovery, ux}'),
('Discovery', 'Benchmarkkaus', 'Benchmarking', '{discovery, market}'),
('Discovery', 'Data‑auditointi', 'Data Audit', '{discovery, data}'),
('Discovery', 'Data‑lähteet', 'Data Sources', '{discovery, data}'),
('Discovery', 'Data‑puutteet', 'Data Gaps', '{discovery, data}'),
('Discovery', 'Discovery‑hypoteesi', 'Discovery Hypothesis', '{discovery, product}'),
('Discovery', 'Dokumentoidut oletukset', 'Documented Assumptions', '{discovery, product}'),
('Discovery', 'Edge‑case‑kartoitus', 'Edge Case Mapping', '{discovery, ux}'),
('Discovery', 'Feature‑fit arvio', 'Feature Fit Assessment', '{discovery, product}'),
('Discovery', 'Fokuskysymykset', 'Focus Questions', '{discovery, product}'),
('Discovery', 'GDPR‑huomiot', 'GDPR Considerations', '{discovery, legal}'),
('Discovery', 'Haastattelukysymykset', 'Interview Questions', '{discovery, ux}'),
('Discovery', 'Haastatteluraportit', 'Interview Summaries', '{discovery, ux}'),
('Discovery', 'Hypoteesien priorisointi', 'Hypothesis Prioritization', '{discovery, product}'),
('Discovery', 'Hypoteesien testaus', 'Hypothesis Testing', '{discovery, product}'),
('Discovery', 'Idean rajaus', 'Idea Scoping', '{discovery, product}'),
('Discovery', 'Insight‑kartta', 'Insight Map', '{discovery, ux}'),
('Discovery', 'Käyttäjähaastattelut', 'User Interviews', '{discovery, ux}'),
('Discovery', 'Käyttäjäongelmat', 'User Pains', '{discovery, ux}'),
('Discovery', 'Käyttäjäprofiilit', 'User Profiles', '{discovery, ux}'),
('Discovery', 'Käyttäjäsegmentointi', 'User Segmentation', '{discovery, ux}'),
('Discovery', 'Käyttäjävirheet', 'User Errors', '{discovery, ux}'),
('Discovery', 'Kilpailija‑analyysi', 'Competitor Analysis', '{discovery, market}'),
('Discovery', 'KPI‑luonnos', 'KPI Draft', '{discovery, business}'),
('Discovery', 'Kysyntäsignaalit', 'Demand Signals', '{discovery, market}'),
('Discovery', 'Markkinadata', 'Market Data', '{discovery, market}'),
('Discovery', 'Markkinatrendit', 'Market Trends', '{discovery, market}'),
('Discovery', 'Mittarit', 'Metrics', '{discovery, business}'),
('Discovery', 'Oletusten validointi', 'Assumption Validation', '{discovery, product}'),
('Discovery', 'Ongelmakuvaus', 'Problem Statement', '{discovery, product}'),
('Discovery', 'Ongelmien juurisyyt', 'Root Causes', '{discovery, product}'),
('Discovery', 'Persona‑tarkistus', 'Persona Check', '{discovery, ux}'),
('Discovery', 'Priorisointikriteerit', 'Prioritization Criteria', '{discovery, product}'),
('Discovery', 'Riskien tunnistus', 'Risk Identification', '{discovery, risk}'),
('Discovery', 'Roadblockit', 'Roadblocks', '{discovery, management}'),
('Discovery', 'Roolit ja vastuut', 'Roles and Responsibilities', '{discovery, management}'),
('Discovery', 'Signaalit', 'Signals', '{discovery, market}'),
('Discovery', 'Stakeholder‑kartta', 'Stakeholder Map', '{discovery, management}'),
('Discovery', 'Suorituskyky‑odotukset', 'Performance Expectations', '{discovery, tech}'),
('Discovery', 'Tarpeiden kartoitus', 'Needs Mapping', '{discovery, ux}'),
('Discovery', 'Tekninen toteutettavuus', 'Technical Feasibility', '{discovery, tech}'),
('Discovery', 'Tiedon puutteet', 'Information Gaps', '{discovery, data}'),
('Discovery', 'Validointisuunnitelma', 'Validation Plan', '{discovery, product}'),
('Discovery', 'Vaikutus vs vaiva', 'Impact vs Effort', '{discovery, product}'),
('Discovery', 'Vaatimusten rajaus', 'Requirement Scoping', '{discovery, product}'),
('Discovery', 'Ymmärrysaukot', 'Knowledge Gaps', '{discovery, product}'),

-- B. IDEOINTI
('Ideointi', 'Aivoriihi', 'Brainstorming', '{ideation, creative}'),
('Ideointi', 'Arvolupaus', 'Value Proposition', '{ideation, business}'),
('Ideointi', 'Arvovirta', 'Value Stream', '{ideation, business}'),
('Ideointi', 'Backlog‑siemenet', 'Backlog Seeds', '{ideation, agile}'),
('Ideointi', 'Design‑vaihtoehdot', 'Design Alternatives', '{ideation, design}'),
('Ideointi', 'Feature‑ideat', 'Feature Ideas', '{ideation, product}'),
('Ideointi', 'Flow‑luonnokset', 'Flow Sketches', '{ideation, ux}'),
('Ideointi', 'Funktio‑rajaukset', 'Functional Boundaries', '{ideation, tech}'),
('Ideointi', 'Ideakortit', 'Idea Cards', '{ideation, creative}'),
('Ideointi', 'Ideapankki', 'Idea Bank', '{ideation, creative}'),
('Ideointi', 'Ideoiden klusterointi', 'Idea Clustering', '{ideation, creative}'),
('Ideointi', 'Käyttötapaukset', 'Use Cases', '{ideation, product}'),
('Ideointi', 'Käyttäjäpolut', 'User Flows', '{ideation, ux}'),
('Ideointi', 'Konseptiluonnokset', 'Concept Sketches', '{ideation, design}'),
('Ideointi', 'Konseptivaihtoehdot', 'Concept Options', '{ideation, design}'),
('Ideointi', 'Low‑fi protot', 'Low‑fidelity Prototypes', '{ideation, design}'),
('Ideointi', 'Mockup‑vaihtoehdot', 'Mockup Options', '{ideation, design}'),
('Ideointi', 'MVP‑rajaukset', 'MVP Boundaries', '{ideation, product}'),
('Ideointi', 'Ongelman uudelleenmuotoilu', 'Reframing', '{ideation, creative}'),
('Ideointi', 'Prototyyppivaihtoehdot', 'Prototype Options', '{ideation, design}'),
('Ideointi', 'Ratkaisupolut', 'Solution Paths', '{ideation, product}'),
('Ideointi', 'Ratkaisun rajaukset', 'Solution Scoping', '{ideation, product}'),
('Ideointi', 'Riskittömät kokeilut', 'Low‑risk Experiments', '{ideation, product}'),
('Ideointi', 'Roolikohtaiset näkymät', 'Role‑based Views', '{ideation, ux}'),
('Ideointi', 'Sketch‑ideat', 'Sketch Ideas', '{ideation, design}'),
('Ideointi', 'Storyboardit', 'Storyboards', '{ideation, ux}'),
('Ideointi', 'Suunnitteluperiaatteet', 'Design Principles', '{ideation, design}'),
('Ideointi', 'Tekninen konsepti', 'Technical Concept', '{ideation, tech}'),
('Ideointi', 'Testattavat ideat', 'Testable Ideas', '{ideation, product}'),
('Ideointi', 'UI‑luonnokset', 'UI Sketches', '{ideation, design}'),
('Ideointi', 'UX‑vaihtoehdot', 'UX Alternatives', '{ideation, ux}'),
('Ideointi', 'Visuaaliset moodit', 'Visual Moods', '{ideation, design}'),

-- C. VAATIMUSMÄÄRITTELY
('Määrittely', 'API‑rajapinnat', 'API Endpoints', '{specs, tech}'),
('Määrittely', 'Audit‑logit', 'Audit Logs', '{specs, tech}'),
('Määrittely', 'Autentikointi', 'Authentication', '{specs, security}'),
('Määrittely', 'Autorisointi', 'Authorization', '{specs, security}'),
('Määrittely', 'Datamallit', 'Data Models', '{specs, data}'),
('Määrittely', 'Edge‑caset', 'Edge Cases', '{specs, product}'),
('Määrittely', 'Error‑tilat', 'Error States', '{specs, ux}'),
('Määrittely', 'Feature‑rajaukset', 'Feature Boundaries', '{specs, product}'),
('Määrittely', 'GDPR‑vaatimukset', 'GDPR Requirements', '{specs, legal}'),
('Määrittely', 'Hyväksymiskriteerit', 'Acceptance Criteria', '{specs, agile}'),
('Määrittely', 'Käyttöoikeudet', 'Permissions', '{specs, security}'),
('Määrittely', 'Käyttöpolut', 'Usage Flows', '{specs, ux}'),
('Määrittely', 'Lokitus', 'Logging', '{specs, tech}'),
('Määrittely', 'Lokalisointi', 'Localization', '{specs, product}'),
('Määrittely', 'Lähdejärjestelmät', 'Source Systems', '{specs, tech}'),
('Määrittely', 'Monitorointi', 'Monitoring', '{specs, ops}'),
('Määrittely', 'Non‑functional requirements', 'Non-functional Requirements', '{specs, tech}'),
('Määrittely', 'Performance‑vaatimukset', 'Performance Requirements', '{specs, tech}'),
('Määrittely', 'Rajapintakuvaukset', 'Interface Descriptions', '{specs, tech}'),
('Määrittely', 'Regressioriskit', 'Regression Risks', '{specs, risk}'),
('Määrittely', 'Resurssirajat', 'Resource Limits', '{specs, tech}'),
('Määrittely', 'Responsiivisuus', 'Responsiveness', '{specs, ux}'),
('Määrittely', 'Skaalautuvuus', 'Scalability', '{specs, tech}'),
('Määrittely', 'Suorituskyky', 'Performance', '{specs, tech}'),
('Määrittely', 'Tietoturva', 'Security', '{specs, security}'),
('Määrittely', 'Tilasiirtymät', 'State Transitions', '{specs, tech}'),
('Määrittely', 'Toiminnalliset vaatimukset', 'Functional Requirements', '{specs, product}'),
('Määrittely', 'Validointisäännöt', 'Validation Rules', '{specs, data}'),
('Määrittely', 'Virheviestit', 'Error Messages', '{specs, ux}'),

-- D. GO-TO-MARKET & JULKAISU
('Go-to-market', 'Adoptiomittarit', 'Adoption Metrics', '{gtm, business}'),
('Go-to-market', 'Beta‑testaus', 'Beta Testing', '{gtm, product}'),
('Go-to-market', 'Dokumentaatio', 'Documentation', '{gtm, product}'),
('Go-to-market', 'FAQ‑luonnos', 'FAQ Draft', '{gtm, support}'),
('Go-to-market', 'Feature‑flagit', 'Feature Flags', '{gtm, tech}'),
('Go-to-market', 'Go‑to‑market‑suunnitelma', 'GTM Plan', '{gtm, business}'),
('Go-to-market', 'Julkaisumuistiot', 'Release Notes', '{gtm, product}'),
('Go-to-market', 'Käyttöönotto', 'Onboarding', '{gtm, ux}'),
('Go-to-market', 'Koulutusmateriaalit', 'Training Materials', '{gtm, support}'),
('Go-to-market', 'Launch‑checklist', 'Launch Checklist', '{gtm, ops}'),
('Go-to-market', 'Mittarit', 'Metrics', '{gtm, business}'),
('Go-to-market', 'Pilotointi', 'Piloting', '{gtm, product}'),
('Go-to-market', 'Rollout‑strategia', 'Rollout Strategy', '{gtm, business}'),
('Go-to-market', 'Riskienhallinta', 'Risk Management', '{gtm, risk}'),
('Go-to-market', 'Regressiotestaus', 'Regression Testing', '{gtm, tech}'),
('Go-to-market', 'Stakeholder‑viestintä', 'Stakeholder Communication', '{gtm, management}'),
('Go-to-market', 'Support‑prosessi', 'Support Process', '{gtm, support}'),
('Go-to-market', 'Tiedotus', 'Announcements', '{gtm, marketing}'),
('Go-to-market', 'Versionhallinta', 'Versioning', '{gtm, tech}'),
('Go-to-market', 'Viestintäpaketti', 'Communication Kit', '{gtm, marketing}'),

-- E. KOMMUNIKAATIO & YHTEISTYÖ
('Kommunikaatio', 'Dev lead ‑synkka', 'Dev Lead Sync', '{comms, tech}'),
('Kommunikaatio', 'Datan tarkistus', 'Data Team Check', '{comms, data}'),
('Kommunikaatio', 'Design‑synkka', 'Design Sync', '{comms, design}'),
('Kommunikaatio', 'Dokumentointipyyntö', 'Documentation Request', '{comms, product}'),
('Kommunikaatio', 'Kysymykset tiimille', 'Team Questions', '{comms, team}'),
('Kommunikaatio', 'Päätösten kirjaus', 'Decision Log', '{comms, management}'),
('Kommunikaatio', 'Riskikeskustelu', 'Risk Discussion', '{comms, risk}'),
('Kommunikaatio', 'Stakeholder‑synkka', 'Stakeholder Sync', '{comms, management}'),
('Kommunikaatio', 'Tekninen arvio', 'Technical Review', '{comms, tech}'),
('Kommunikaatio', 'UX‑arvio', 'UX Review', '{comms, design}'),
('Kommunikaatio', 'Viikkosynkka', 'Weekly Sync', '{comms, management}'),
('Kommunikaatio', 'Workshop‑agenda', 'Workshop Agenda', '{comms, management}'),

-- F. TYÖKALUT & TEKNOLOGIAT
('Työkalut', 'Analytiikka: Posthog', 'Analytics: Posthog', '{tools, data}'),
('Työkalut', 'Design: Figma', 'Design: Figma', '{tools, design}'),
('Työkalut', 'Dokumentointi: Notion', 'Documentation: Notion', '{tools, product}'),
('Työkalut', 'Kaaviot: Miro', 'Diagrams: Miro', '{tools, design}'),
('Työkalut', 'Koodivarasto: GitHub', 'Code Repo: GitHub', '{tools, tech}'),
('Työkalut', 'Projektinhallinta: Linear', 'Project Management: Linear', '{tools, management}'),
('Työkalut', 'Protot: Figma', 'Prototypes: Figma', '{tools, design}'),
('Työkalut', 'Tietokanta: Supabase', 'Database: Supabase', '{tools, tech}'),
('Työkalut', 'Videot: Loom', 'Videos: Loom', '{tools, comms}');
